### ISSUE TITLE
Performance issues with large / many templates (though they're not rendered)

### ISSUE THREAD

**Issue by chrissound** [snapframework/heist#102]
So I've been trying to figure out why a simple template is taking a very long time to render (nearly a second). I realized my heist config was trying to compile the templates - I've prevented that.

However it's still taking 0.2s, upon further investigation if I add a bunch of large templates into my templates directory - the performance drops. I'm not rendering those templates so I don't see why any processing is being done on them. 

Here is my function I use to render:
```
renderHeistTemplatePath :: TemplateName -> HeistBind -> IO (Either Text Text)
renderHeistTemplatePath fileName hsBinding = do
  let emptyI = return () :: MapSyntax Text (I.Splice IO)
  let emptyC = return () :: MapSyntax Text (HeistCom.Splice IO)
  let emptyA = return () :: MapSyntax Text (AttrSplice IO)
  let templateLocations = [Heist.loadTemplates "templates/"]
  let spliceConfig = SpliceConfig emptyI emptyI emptyC emptyA templateLocations (\_ -> False):: SpliceConfig IO
  heist <- Heist.initHeist (HeistConfig spliceConfig "" True)
  case heist of
    Right heist' -> do
      rendered <- I.renderTemplate (hsBinding heist') $ convertString fileName
      case (rendered) of
        Just (builder, _) -> return . return . convertString $ toLazyByteString builder
        Nothing -> return . Left $ "Heist render error. No further information"
    Left a -> return . Left . convertString . show $ a
```

Any ideas would greatly be appreciated.

**Comment by chrissound** [comment]
If I keep adding templates to the /`templates/` directory - the performance keeps droping.

**Comment by mightybyte** [comment]
It looks like this is because you're loading the templates, initializing heist, and rendering all in one step.  Heist was designed to do as much work as possible up front in the `initHeist` function so that all successive calls to `renderTemplate` are as fast as possible.  Templates are not lazily loaded because it's doing all XML/HTML syntax checking up front so it can fail fast if you have any syntax errors.  Lazy loading would also make things slower the first time a new template is rendered.

I would suggest not counting the `initHeist` time in your measure of performance.  Call `initHeist` once and keep the resulting `HeistState` around for the rest of the life of your app.  If for some reason you can't do this, then I would suggest splitting your templates across separate directories, so `initHeist` doesn't have to load as many templates.

In this example it doesn't look like you're doing any runtime splice substitution.  If that's the case, maybe you would be better off serving them statically instead of using Heist.

**Comment by chrissound** [comment]
That explains it, thanks.
