### ISSUE TITLE
How to pass raw HTML as template variable?

### ISSUE THREAD

**Issue by srid** [snapframework/heist#126]
`textSplice` cannot obviously be used to inject raw HTML (say, those coming from Pandoc rendered HTML) into heist template, as they will be automatically escaped.

One solution is to parse the raw HTML using `Text.XmlHtml` but this is obviously both unnecessary and waste of CPU usage.

Does heist support injecting raw HTML?

---

A related question: if I'm to build HTML from some AST (say Pandoc AST), how does the performance of `Text.XmlHtml` compare to others (such as blaze-html)?

**Comment by mightybyte** [comment]
Check out the `Chunk` data type's `RuntimeHtml` constructor:

https://hackage.haskell.org/package/heist-1.1.0.1/docs/Heist-Internal-Types.html#t:Chunk

I'm not aware of any published benchmarks comparing the performance of `xmlhtml` to other libraries.  The main motivation behind `xmlhtml` was to make a library that supported flexible tag sets that you end up wanting to handle the custom tag approach used by heist.  I'd be very interested to see performance numbers if you end up doing any comparison.

**Comment by cdsmith** [comment]
If I had to guess, I'd guess that xmlhtml parsing performance is terrible, but rendering probably performs somewhere in the same order of magnitude with other approaches.  Parsing was never treated as a performance-critical use case, since the assumption was that you will parse your templates once, and that they will be relatively small since any iteration or dynamic data is inserted with splices.  Benchmarking will give you a better answer, though.  If your benchmarks disagree with that guess, I would be interested.
