### ISSUE TITLE
Barely malformed XML

### ISSUE THREAD

**Issue by andrewthad** [snapframework/heist#58]
So, when I use heist for XML (or HTML, but I assume that it probably leads to correct behaviors in that case), the end of the resulting document looks like this:

    </office:body>&#10;</office:document-content>&#10;

When I run this file through xmllint, I get:

    andrew@webapps-test:~/projects/sheets$ xmllint --format sheet.xml                                                                                                                                            
    sheet.xml:6: parser error : Extra content at the end of the document
    </table:table></office:spreadsheet></office:body>&#10;</office:document-content>
                                                                                   ^
Other linters give similar complaints. This is because you aren't supposed to have any content after closing the root tag in an XML document. Is there something that I have missed (ie- rendering it the wrong way), or is this case not correctly handled?

**Comment by mightybyte** [comment]
This issue has been around for a long time and is described here.  Fixing it requires a decent amount of work to xmlhtml though, which is why nobody has gotten around to fixing it.  While it does cause these validation errors you're seeing and increase the size of your markup a bit, on the whole it's relatively harmless, thus the lack of motivation.
