### ISSUE TITLE
Incorrect alignment in resulting HTML

### ISSUE THREAD

**Issue by snap9** [snapframework/heist#89]
Consider this .tpl file:

    <html>
    <head>
        <apply template="meta"/>
    </head>
    </html>

With this meta.tpl file:

    <meta http-equiv='content-type' content='text/html; charset=utf-8' />
    <meta name='robots' content='noarchive' />

Then this is the result:

    <html>
    <head>
        <meta http-equiv='content-type' content='text/html; charset=utf-8' />
    <meta name='robots' content='noarchive' />
    </head>
    </html>

Note the misalignment of the second line.

Can this be fixed? (I like my websites to have beautiful HTML.)

**Comment by snap9** [comment]
On the second thought, I see the sensibility of inserting things from meta.tpl exactly as they are. (Since there are cases where extra spaces might screw things up.)

But IMO it would be nice if I could pass in an "pretty-align" option for each apply or splice.

**Comment by mightybyte** [comment]
I don't think we can do this automatically because whitespace is significant in HTML.  This is also why we don't have something that generates compact output, which I mentioned in https://github.com/snapframework/heist/issues/8#issuecomment-12327955.

**Comment by snap9** [comment]
What about adding an optional setting for it? (People could then use it when they know the whitespace won't cause harm.)

For example:

    <apply template="meta" settings="respect-surrounding-indentation"/>

**Comment by snap9** [comment]
Hey again, what do you think? Would be nice to get more control like that over the output in regards to spaces and newlines.

**Comment by cdsmith** [comment]
Just personal opinion here.

If you want nicely-formatted output for whatever reason (perhaps you're generating user-visible example code?), you should probably format the output.  Tangling it in with Heist's evaluation feels like an overly complicated solution that fails to separate concerns.

Even if you did want to build this into Heist, I doubt that you really want to make that decision about indentation on a case-by-case basis every time you apply a splice, as in your last comment.  You more likely want to make it a global or request-level option.  Then you need to decide how to deal with cases (like HTML `pre` tags, for instance) where this would behave very badly.  One answer is to maintain a database of these cases, but I suppose I could imagine some kind of more dynamic way of tagging sections of the document to leave alone.

**Comment by mightybyte** [comment]
I tend to agree with @cdsmith.  It definitely could not be something done at the splice level because a single splice can appear at all kinds of different indentation levels.  Heist would need some kind of flag.  I think you'd probably need three different cases: pretty, compact, and no change.  These kinds of options work better for things like blaze when you have `p "This is a paragraph"`.  In heist, you usually have this:

```
<p>
  This is a paragraph
</p>
```

This would be equivalent to the blaze expression `p "\n  This is a paragraph\n"`.  And like I said before, whitespace is significant in HTML.  I think running a pretty printer after the fact to reformat Heist's output would actually be pretty efficient and straightforward to write.  (There's got to be something out there that already does this.  Maybe not in Haskell though.)  You shouldn't have to re-parse the whole document.  It should be sufficient to just track the current tag nesting level and output or eat the appropriate spacing in a single pass.

I'm going to close this for now, but feel free to continue the discussion.  It's definitely a relevant issue, and I'm open to changing my mind if the argument is strong.
